site_name: inventorycount
site_description: Centro full stack interview exercise
repo_url: https://github.com/andrewliu-centro/centro-fullstack-exercise
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/andrewliu-centro">andrewliu-centro</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
